steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup JDK
    uses: actions/setup-java@v3
    with:
      distribution: 'zulu'
      java-version: '17'

  - name: Build and Test with JaCoCo
    run: ./gradlew build jacocoTestReport
  - name: JaCoCo Code Coverage Report
    id: jacoco_reporter
    uses: PavanMudigonda/jacoco-reporter@v4.8
    with:
      coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
      coverage_report_name: Coverage
      coverage_report_title: JaCoCo
      github_token: ${{ secrets.GITHUB_TOKEN }}
      skip_check_run: false
      minimum_coverage: 80
      fail_below_threshold: false
      publish_only_summary: false
